CREATE TABLE Trip (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, description TEXT, start_date TEXT, end_date TEXT, pending_create INTEGER, pending_update INTEGER, pending_delete INTEGER);
CREATE TABLE Country (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, description TEXT, wikipedia_url TEXT, wikitravel_url TEXT, plug INTEGER, currency INTEGER, languages INTEGER, plug_frequency TEXT, plug_voltage TEXT);
CREATE TABLE City (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, description TEXT, wikipedia_url TEXT, wikitravel_url TEXT, country INTEGER, timezone INTEGER, lat DECIMAL, lng DECIMAL);
CREATE TABLE CityVisit(id INTEGER PRIMARY KEY AUTOINCREMENT, trip INTEGER, city INTEGER, date TEXT, pending_create INTEGER, pending_update INTEGER, pending_delete INTEGER);
CREATE TABLE Place(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, city INTEGER, description TEXT, lat DECIMAL, lng DECIMAL, wikipedia_url TEXT, recommended INTEGER);
CREATE TABLE PlaceVisit(id INTEGER PRIMARY KEY AUTOINCREMENT, trip INTEGER, place INTEGER, date TEXT, ordenation INTEGER, pending_create INTEGER, pending_update INTEGER, pending_delete INTEGER);
CREATE TABLE Currency(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, code TEXT, rate DECIMAL);
CREATE TABLE Plug(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, description TEXT, image TEXT);
CREATE TABLE Language(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, code TEXT);
CREATE TABLE Transport(id INTEGER PRIMARY KEY AUTOINCREMENT, trip INTEGER, origin INTEGER, destination INTEGER, place TEXT, date TEXT, code TEXT, reservation TEXT, type TEXT, pending_create INTEGER, pending_update INTEGER, pending_delete INTEGER);